---
- hosts: master
  vars:
  become: yes
  tasks:
    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl set image deployment/blogr-app blogr-app=denzal/blogr:latest --namespace=blogr
#TODO: implement version variable instead of latest