---
#TODO: check why curl cant't work in this playbook
- hosts: master
  become: yes
  tasks:
    - name: Download Helm install script
      get_url: 
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get
        dest: get_helm.sh

    # shell: 'curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh'

    - name: Change rights to script file
      file: 
        path: "./get_helm.sh"
        mode: a+x

    - name: Run Helm install Script
      command: sh ./get_helm.sh

    - name: Rin Helm Initialization
      shell: "helm init"